### ISSUE TITLE
TcpServer.h:5:10: fatal error: 'Object.h' file not found

### ISSUE THREAD

**Issue by revikiran1991** [unrealcv/unrealcv#143]
- Operating System:Ubuntu 18.04
- UE4 Version:4.20.2
- UnrealCV Version: https://github.com/unrealcv/unrealcv.git
- Client (python2, 3 or matlab):python2
- Problem Description:
  ------------------------------
  Performing 3 actions (2 in parallel)
  [1/3] Compile Module.UnrealCV.cpp
  [2/3] Compile Module.UnrealCV.gen.cpp
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealCV/Module.UnrealCV.gen.cpp:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealCV/GTCaptureComponent.gen.cpp:8:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/GTCaptureComponent.h:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/UE4CVServer.h:5:
  /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/TcpServer.h:5:10: fatal error: 'Object.h' file not found
  #include "Object.h"
           ^~~~~~~~~~
  1 error generated.
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealCV/Module.UnrealCV.cpp:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Private/CaptureManager.cpp:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/CaptureManager.h:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/GTCaptureComponent.h:2:
  In file included from /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/UE4CVServer.h:5:
  /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Public/TcpServer.h:5:10: fatal error: 'Object.h' file not found
  #include "Object.h"
           ^~~~~~~~~~
  1 error generated.
  ERROR: UBT ERROR: Failed to produce item: /home/ravi/Downloads/unrealcv-master/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Binaries/Linux/libUE4Editor-UnrealCV.so
         (see /home/ravi/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UE4Editor-Linux-Development.txt for full exception trace)
  Total build time: 186.07 seconds (Local executor: 0.00 seconds)
Took 187.031198s to run mono, ExitCode=5
ERROR: UnrealBuildTool failed. See log for more details. (/home/ravi/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UE4Editor-Linux-Development.txt)
       (see /home/ravi/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
AutomationTool exiting with ExitCode=5 (5)
RunUAT ERROR: AutomationTool was unable to run successfully.

Please help me to remove this bug. I tried finding this file but, was not successful.

**Comment by liorda** [comment]
See PR https://github.com/unrealcv/unrealcv/pull/146 which fixes the build on 4.20.3
