### ISSUE TITLE
Build failed for UE4.26

### ISSUE THREAD

**Issue by gaoyuanzizizi** [unrealcv/unrealcv#217]
- Operating System:
- UE4 Version:4.26
- UnrealCV Version:3.0.10
- Client (python2, 3 or matlab): python3
- Problem Description:
I have tried to build UnrealCV for UE4.26 but it has failed.  Can you please inform whether there is any support for this or not?

$ python build.py --UE "E:\Program Files\Epic Games\UE_4.26"
Running AutomationTool...
Parsing command line: BuildPlugin -plugin=E:\PythonDocuments\unrealcv-0.3.10\UnrealCV.uplugin -package=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV -rocket -targetplatforms=Win64
Copying 138 file(s) using max 64 thread(s)
Reading plugin from E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\UnrealCV.uplugin...
Building plugin for host platforms: Win64
Running: E:\Program Files\Epic Games\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -Project=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\HostProject.uproject -plugin=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\UnrealCV.uplugin -iwyu -noubtmakefiles -manifest=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml -nohotreload -log="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Program+Files+Epic+Games+UE_4.26\UBT-UE4Editor-Win64-Development.txt"
  While compiling E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Intermediate\Build\BuildRules\HostProjectModuleRules.dll:
  e:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\Source\UnrealCV\UnrealCV.Build.cs(18,41) : error CS0122: “UnrealBuildTool.BuildConfiguration”不可访问，因为它受保护级别限制
  e:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\Source\UnrealCV\UnrealCV.Build.cs(51,8) : error CS0103: 当前上下文中不存在名称“UEBuildConfiguration”
  ERROR: Unable to compile source files.
Took 2.661s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Program+Files+Epic+Games+UE_4.26\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

**Comment by florian-world** [comment]
I just pushed a new 4.26 branch on my fork [https://github.com/florian-world/unrealcv/tree/4.26](https://github.com/florian-world/unrealcv/tree/4.26) which I used successfully to compile a new world with Unreal Engine 4.26.2 on Ubuntu 20.04.

If this is of any use, perhaps @qiuwch can pull it to a new 4.26 branch here.

**Comment by dr-smgad** [comment]
Hi florian, many thanks for sharing this branch, it build with UE 4.26.2 successfully on Windows. Yet, when I am trying to launch the Shooter game sample with the plugin, I am getting an assertion error as below:

![image](https://user-images.githubusercontent.com/80755241/168164277-6e380233-c3ea-4522-a623-82133d58c91d.png)
